MagbBundle\Entity\Categorie:
    type: entity
    table: Categorie
    id:
        idcat:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: idCat
            generator:
                strategy: IDENTITY
    fields:
        nomcat:
            type: string
            nullable: false
            length: 128
            fixed: false
            column: nomCat
    lifecycleCallbacks: {  }
