MagbBundle\Entity\Souscategorie:
    type: entity
    table: SousCategorie
    id:
        idsouscat:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: idSousCat
            generator:
                strategy: IDENTITY
    fields:
        nomsouscat:
            type: string
            nullable: false
            length: 64
            fixed: false
            column: nomSousCat
        idcat:
            type: integer
            nullable: true
            unsigned: false
            column: idCat
    lifecycleCallbacks: {  }
