MagbBundle\Entity\Ville:
    type: entity
    table: Ville
    id:
        idville:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: idVille
            generator:
                strategy: IDENTITY
    fields:
        ville:
            type: string
            nullable: false
            length: 64
            fixed: false
        cp:
            type: integer
            nullable: false
            unsigned: false
            column: CP
    lifecycleCallbacks: {  }
